/**
 * Tamil Nadu disaster record, 2016-2025.
 *
 * GENERATED by tools/build-tn-history.mjs from the CSVs in data/. Do not edit
 * by hand; edit the sources and re-run.
 *
 * 27 events, of which 12 are hydro-meteorological and
 * therefore the only ones this application's flood model has any business
 * reading. The rest - fireworks factory explosions, boiler blasts, a rail
 * collision - are kept because they are part of the district's incident
 * record and shape response capacity, but they are tagged isHydro: false and
 * never reach the flood engine.
 *
 * This is a record of what happened, not a training set. 12 events
 * cannot calibrate a hydrological model, and only 1 carry a
 * documented rainfall figure at all. It is used for historical precedent and
 * for validating that the model's predictions are not absurd - nothing more.
 */

export interface TnDisasterEvent {
  id: string;
  name: string;
  year: number;
  /** As written in the source: may be a range, or a month rather than a day. */
  date: string;
  hazard:
    | 'cyclone'
    | 'flood'
    | 'drought'
    | 'fireworks'
    | 'industrial'
    | 'transport'
    | 'structural'
    | 'other';
  /** True for cyclone, flood, rain and drought events only. */
  isHydro: boolean;
  /** Census 2011 district names, matching the bundled polygons. */
  districts: string[];
  /**
   * Districts that were named in the source but created after 2011, so the
   * entry above is the parent district standing in for them.
   */
  substitutedDistricts: string[];
  centers: [number, number][];
  deaths: number | null;
  /** Set only where the source cell held more than one figure. */
  deathsRaw: string | null;
  injuries: number | null;
  evacuated: number | null;
  damageCrore: number | null;
  damageBasis: string | null;
  /** Documented rainfall for the event, mm. Null where none was published. */
  rainfallMm: number | null;
  windKmh: number | null;
  infrastructure: string | null;
  sourceType: string;
  source: string;
  sourceUrl: string | null;
  limitations: string | null;
  notes?: string | null;
  /** Figures from the other source file that disagree with the one above. */
  variants: string[];
}

export const TN_DISASTERS: TnDisasterEvent[] = [
  {
    "id": "TNS-2016-vardah",
    "name": "Cyclone Vardah",
    "year": 2016,
    "date": "2016 December",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvallur",
      "Kancheepuram",
      "Chennai"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        13.2495,
        79.8749
      ],
      [
        12.7346,
        79.8593
      ],
      [
        13.0833,
        80.2582
      ]
    ],
    "deaths": 18,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": null,
    "rainfallMm": null,
    "windKmh": 130,
    "infrastructure": null,
    "sourceType": "Summary dataset",
    "source": "tn_disasters_dataset.csv",
    "sourceUrl": null,
    "limitations": "From the summary dataset, which carries no per-event source URL. Treat as indicative.",
    "notes": "Landfall near Chennai; widespread tree and power-line damage",
    "variants": []
  },
  {
    "id": "TNS-2018-gaja",
    "name": "Cyclone Gaja",
    "year": 2018,
    "date": "2018 November",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvarur",
      "Nagappattinam",
      "Pudukkottai",
      "Cuddalore",
      "Ramanathapuram",
      "Thanjavur"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        10.6587,
        79.5655
      ],
      [
        10.894,
        79.7045
      ],
      [
        10.3965,
        78.9026
      ],
      [
        11.6364,
        79.4948
      ],
      [
        9.5189,
        78.6457
      ],
      [
        10.5941,
        79.2461
      ]
    ],
    "deaths": 45,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": 250000,
    "damageCrore": null,
    "damageBasis": null,
    "rainfallMm": null,
    "windKmh": 165,
    "infrastructure": "115000 houses damaged",
    "sourceType": "Summary dataset",
    "source": "tn_disasters_dataset.csv",
    "sourceUrl": null,
    "limitations": "From the summary dataset, which carries no per-event source URL. Treat as indicative.",
    "notes": "Very severe cyclonic storm; heavy damage across delta districts",
    "variants": []
  },
  {
    "id": "TN2019-01",
    "name": "Hydrological drought declaration",
    "year": 2019,
    "date": "2019-03-07",
    "hazard": "drought",
    "isHydro": true,
    "districts": [
      "Thoothukkudi",
      "Kanniyakumari",
      "The Nilgiris",
      "Tiruppur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Erode",
      "Krishnagiri",
      "Madurai",
      "Ramanathapuram",
      "Salem",
      "Thanjavur",
      "Theni",
      "Tiruchirappalli",
      "Tirunelveli",
      "Vellore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        8.9003,
        78.0032
      ],
      [
        8.3245,
        77.365
      ],
      [
        11.4471,
        76.5987
      ],
      [
        10.8482,
        77.3985
      ],
      [
        13.0833,
        80.2582
      ],
      [
        10.9317,
        76.9717
      ],
      [
        11.6364,
        79.4948
      ],
      [
        12.0968,
        78.2538
      ],
      [
        11.4898,
        77.3503
      ],
      [
        12.4804,
        78.0716
      ],
      [
        9.903,
        78.0481
      ],
      [
        9.5189,
        78.6457
      ],
      [
        11.629,
        78.2579
      ],
      [
        10.5941,
        79.2461
      ],
      [
        9.9319,
        77.4373
      ],
      [
        10.8314,
        78.5587
      ],
      [
        8.839,
        77.5998
      ],
      [
        12.8292,
        79.1011
      ]
    ],
    "deaths": 0,
    "deathsRaw": null,
    "injuries": 0,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "Not available",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Water resources/reservoir storage and drinking-water systems under stress; crop impacts reported",
    "sourceType": "Verified government gazette; corroborating media",
    "source": "TN Government Extraordinary Gazette G.O.Ms.No.91 (07-03-2019); DT Next",
    "sourceUrl": "https://www.stationeryprinting.tn.gov.in/extra_ordinary_lists.php?id=MjAxOQ%3D%3D",
    "limitations": "Drought is a slow-onset hazard; taluk-level human/infrastructure loss and a single INR damage total are not provided in the cited declaration.",
    "variants": []
  },
  {
    "id": "TN2019-02",
    "name": "North-East Monsoon heavy rain and flooding",
    "year": 2019,
    "date": "2019-11-29/2019-12-02",
    "hazard": "flood",
    "isHydro": true,
    "districts": [
      "Thoothukkudi",
      "Kancheepuram",
      "Chennai",
      "Cuddalore",
      "Tirunelveli"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        8.9003,
        78.0032
      ],
      [
        12.7346,
        79.8593
      ],
      [
        13.0833,
        80.2582
      ],
      [
        11.6364,
        79.4948
      ],
      [
        8.839,
        77.5998
      ]
    ],
    "deaths": 25,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": 1000,
    "damageCrore": 1.21,
    "damageBasis": "₹1.209 crore reported to CWC for 2019 flood damage; likely incomplete relative to broader rain losses",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "2814 houses; 230 cattle; local flooding/inundation",
    "sourceType": "Government database + media",
    "source": "CWC/PIB flood-damage statement; New Indian Express",
    "sourceUrl": "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1797322&lang=2&reg=48",
    "limitations": "Official CWC table reports a very low aggregate monetary figure and may not capture all sectoral losses.",
    "variants": []
  },
  {
    "id": "TN2019-03",
    "name": "Nadur/Mettupalayam compound-wall collapse",
    "year": 2019,
    "date": "2019-12-02",
    "hazard": "structural",
    "isHydro": false,
    "districts": [
      "Coimbatore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        10.9317,
        76.9717
      ]
    ],
    "deaths": 17,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No reliable event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Compound wall and four houses collapsed/damaged",
    "sourceType": "Government parliamentary record + media",
    "source": "Lok Sabha debate, 06-12-2019; Indian Express/New Indian Express",
    "sourceUrl": "https://sansad.in/getFile/debatestextmk/17/II/6.12.2019.pdf?source=loksabhadocs",
    "limitations": "No standardized event-level economic-loss assessment was found.",
    "variants": []
  },
  {
    "id": "TN2020-01",
    "name": "NLC Neyveli TPS-II Unit VI boiler blast",
    "year": 2020,
    "date": "2020-05-07",
    "hazard": "industrial",
    "isHydro": false,
    "districts": [
      "Cuddalore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        11.6364,
        79.4948
      ]
    ],
    "deaths": 0,
    "deathsRaw": null,
    "injuries": 8,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level figure located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Boiler/unit; generation temporarily halted",
    "sourceType": "Company/government-linked official release + media",
    "source": "NLC India press reporting; India Today/NDTV",
    "sourceUrl": "https://www.indiatoday.in/india/story/boiler-explosion-neyveli-lignite-corporation-cuddalore-tamil-nadu-1675424-2020-05-07",
    "limitations": "Detailed repair cost and final medical outcomes were not found in the cited sources.",
    "variants": []
  },
  {
    "id": "TN2020-02",
    "name": "NLC Neyveli TPS-II Unit V boiler blast",
    "year": 2020,
    "date": "2020-07-01",
    "hazard": "industrial",
    "isHydro": false,
    "districts": [
      "Cuddalore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        11.6364,
        79.4948
      ]
    ],
    "deaths": 15,
    "deathsRaw": null,
    "injuries": 17,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level property-loss total located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Boiler supporting structure, lift and cable; generating units temporarily shut for safety audit",
    "sourceType": "Verified official/company + NGT/CPCB report",
    "source": "NLC India press release; NGT/CPCB independent report",
    "sourceUrl": "https://nsearchives.nseindia.com/corporate/NLCINDIA_01072020212058_PressRelease01.pdf",
    "limitations": "Media initially reported lower death counts; final NGT/CPCB material gives 15 deaths. No consolidated INR damage estimate.",
    "variants": []
  },
  {
    "id": "TN2020-03",
    "name": "Cyclone Nivar",
    "year": 2020,
    "date": "2020-11-25/2020-11-27",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvallur",
      "Kancheepuram",
      "Viluppuram",
      "Chennai",
      "Cuddalore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        13.2495,
        79.8749
      ],
      [
        12.7346,
        79.8593
      ],
      [
        11.9551,
        79.3582
      ],
      [
        13.0833,
        80.2582
      ],
      [
        11.6364,
        79.4948
      ]
    ],
    "deaths": 6,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": 125000,
    "damageCrore": 3758.55,
    "damageBasis": "₹3,758.55 crore state assistance sought for relief/restoration; this is a damage/assistance estimate, not final realized loss",
    "rainfallMm": null,
    "windKmh": 120,
    "infrastructure": "4398 houses/huts; 60 fishermen boats/nets; crops 0.16 lakh ha; roads, electricity and civic assets damaged",
    "sourceType": "Verified government/IMD/MHA + media",
    "source": "IMD Annual Report 2020; MHA parliamentary answer; Indian Express",
    "sourceUrl": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1697644&lang=2&reg=48",
    "limitations": "The ₹3,758.55 crore is requested assistance, not a final audited loss total.",
    "variants": [
      "12 deaths reported in the summary dataset"
    ],
    "notes": "Major flooding; followed days later by weaker Cyclone Burevi"
  },
  {
    "id": "TN2020-04",
    "name": "Cyclone Burevi",
    "year": 2020,
    "date": "2020-12-01/2020-12-05",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Nagappattinam",
      "Thoothukkudi",
      "Kanniyakumari",
      "Tirunelveli",
      "Cuddalore",
      "Ramanathapuram",
      "Thanjavur"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        10.894,
        79.7045
      ],
      [
        8.9003,
        78.0032
      ],
      [
        8.3245,
        77.365
      ],
      [
        8.839,
        77.5998
      ],
      [
        11.6364,
        79.4948
      ],
      [
        9.5189,
        78.6457
      ],
      [
        10.5941,
        79.2461
      ]
    ],
    "deaths": 7,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": 1514.06,
    "damageBasis": "₹1,514.06 crore central assistance sought by Tamil Nadu; not a final audited loss",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "5509 houses/huts; 719 cattle; 2.00 lakh ha cropped area; 29 boats/nets",
    "sourceType": "Verified MHA + media",
    "source": "MHA parliamentary answer; Times of India",
    "sourceUrl": "https://xn--i1b5bzbybhfo5c8b4bxh.xn--11b7cb3a6a.xn--h2brj9c/MHA1/Par2017/pdfs/par2021-pdfs/rs-17032021/2432.pdf",
    "limitations": "No single verified final economic-loss total was found.",
    "variants": [],
    "notes": "Small tropical storm; limited impact in TN vs Sri Lanka"
  },
  {
    "id": "TN2021-01",
    "name": "Heavy rain and flood episode assessed by IMCT in February 2021",
    "year": 2021,
    "date": "2021-01/2021-02",
    "hazard": "flood",
    "isHydro": true,
    "districts": [],
    "substitutedDistricts": [],
    "centers": [],
    "deaths": null,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": 213.51,
    "damageBasis": "₹213.51 crore NDRF assistance approved following IMCT assessment",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Flood-related houses/crops/public assets; detailed event table not available in cited source",
    "sourceType": "Verified Government of India",
    "source": "MHA 2026 parliamentary answer listing calamity-wise NDRF assistance",
    "sourceUrl": "https://www.mha.gov.in/MHA1/Par2017/pdfs/par2026-pdfs/RS18032026/2957.pdf",
    "limitations": "Included to preserve an officially recognized 2020-21 flood episode; detailed local data require the underlying IMCT report.",
    "variants": []
  },
  {
    "id": "TN2021-02",
    "name": "Sattur/Achankulam fireworks factory blast",
    "year": 2021,
    "date": "2021-02-12/2021-02-13",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 19,
    "deathsRaw": null,
    "injuries": 20,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No reliable event-level property-loss figure located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Factory rooms/buildings heavily damaged",
    "sourceType": "Media reports; government relief actions referenced",
    "source": "Indian Express; Times of India",
    "sourceUrl": "https://indianexpress.com/article/india/tamil-nadu-firecracker-factory-death-7185922/",
    "limitations": "Taluk/location is clear; exact injury total and property-loss valuation vary across reports.",
    "variants": []
  },
  {
    "id": "TN2021-03",
    "name": "Crimsun Organics boiler blast",
    "year": 2021,
    "date": "2021-05-13",
    "hazard": "industrial",
    "isHydro": false,
    "districts": [
      "Cuddalore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        11.6364,
        79.4948
      ]
    ],
    "deaths": 4,
    "deathsRaw": null,
    "injuries": 15,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Boiler/plant area; fire and smoke damage",
    "sourceType": "Media report citing police/officials",
    "source": "Indian Express; New Indian Express; India Today",
    "sourceUrl": "https://www.newindianexpress.com/states/tamil-nadu/2021/May/14/four-killed-13-injured-in-boiler-blast-in-cuddalore-district-2302238.html",
    "limitations": "Different reports gave 13, 15 and 20 injured; dataset flags this discrepancy rather than selecting an unsupported number.",
    "variants": []
  },
  {
    "id": "TN2021-04",
    "name": "North-East Monsoon floods and urban flooding",
    "year": 2021,
    "date": "2021-11-01/2021-11-15",
    "hazard": "flood",
    "isHydro": true,
    "districts": [
      "Thiruvallur",
      "Thiruvarur",
      "Nagappattinam",
      "Kancheepuram",
      "Viluppuram",
      "Vellore",
      "Chennai",
      "Cuddalore",
      "Thanjavur",
      "Tiruvannamalai"
    ],
    "substitutedDistricts": [
      "Vellore"
    ],
    "centers": [
      [
        13.2495,
        79.8749
      ],
      [
        10.6587,
        79.5655
      ],
      [
        10.894,
        79.7045
      ],
      [
        12.7346,
        79.8593
      ],
      [
        11.9551,
        79.3582
      ],
      [
        12.8292,
        79.1011
      ],
      [
        13.0833,
        80.2582
      ],
      [
        11.6364,
        79.4948
      ],
      [
        10.5941,
        79.2461
      ],
      [
        12.4223,
        79.2542
      ]
    ],
    "deaths": 14,
    "deathsRaw": "14 reported by 12 Nov; annual government hydro-meteorological series later reports 128 for FY 2021-22",
    "injuries": null,
    "evacuated": 9312,
    "damageCrore": 6230.45,
    "damageBasis": "₹6,230.45 crore total sought in Tamil Nadu memoranda for the 2021 North-East Monsoon event; not a final audited loss",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "1146 huts and 237 houses completely damaged in one 12-Nov snapshot; broader government series reports 48,510 houses/huts damaged for FY 2021-22 floods",
    "sourceType": "Government of India + media",
    "source": "MHA/NDRF records; Indian Express",
    "sourceUrl": "https://sansad.in/getFile/loksabhaquestions/annex/184/AU288_lZFPXC.pdf?source=pqals",
    "limitations": "The 128-death annual figure covers the FY 2021-22 hydro-meteorological disaster series and should not be treated as the exact toll for the November snapshot.",
    "variants": []
  },
  {
    "id": "TN2022-01",
    "name": "Kalathur/Nathampatti fireworks blast",
    "year": 2022,
    "date": "2022-01-01",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 4,
    "deathsRaw": null,
    "injuries": 7,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "About three rooms collapsed; unit heavily damaged",
    "sourceType": "Media report",
    "source": "New Indian Express; Times of India",
    "sourceUrl": "https://www.newindianexpress.com/states/tamil-nadu/2022/Jan/01/four-workers-die-in-explosion-at-firecracker-unit-in-tamil-nadu-seven-injured-2401983.html",
    "limitations": "Taluk-level administrative naming is inconsistent across reports.",
    "variants": []
  },
  {
    "id": "TN2022-02",
    "name": "M Puthur fireworks unit blast",
    "year": 2022,
    "date": "2022-06-23",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Cuddalore"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        11.6364,
        79.4948
      ]
    ],
    "deaths": 3,
    "deathsRaw": null,
    "injuries": 2,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Factory unit destroyed/flattened",
    "sourceType": "Media report",
    "source": "India Today; Indian Express",
    "sourceUrl": "https://indianexpress.com/article/cities/chennai/tamil-nadu-firecracker-unit-blast-death-toll-relief-7987069/",
    "limitations": "No official event-level damage valuation located.",
    "variants": []
  },
  {
    "id": "TN2023-01",
    "name": "Krishnagiri fireworks factory blast",
    "year": 2023,
    "date": "2023-07-29",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Krishnagiri"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        12.4804,
        78.0716
      ]
    ],
    "deaths": 8,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "At least four buildings damaged; nearby hotel building collapsed",
    "sourceType": "Media report",
    "source": "India Today",
    "sourceUrl": "https://www.indiatoday.in/india/story/8-killed-as-buildings-collapse-due-to-explosion-at-tamil-nadu-cracker-factory-2413425-2023-07-29",
    "limitations": "Final injury count and economic damage not consistently published.",
    "variants": []
  },
  {
    "id": "TN2023-02",
    "name": "Virudhunagar fireworks-unit fires",
    "year": 2023,
    "date": "2023-10",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 11,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level combined estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Fireworks units damaged; exact asset counts not consolidated",
    "sourceType": "Media report",
    "source": "India Today report summarizing the two 2023 incidents",
    "sourceUrl": "https://www.indiatoday.in/amp/india/tamil-nadu/story/blast-at-firecracker-factory-in-tamil-nadu-virudhunagar-dead-injured-2537165-2024-05-09",
    "limitations": "Two separate incidents are aggregated because the cited source does not provide a complete structured record for each.",
    "variants": []
  },
  {
    "id": "TN2023-03",
    "name": "Cyclone Michaung",
    "year": 2023,
    "date": "2023-12-03/2023-12-05",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvallur",
      "Kancheepuram",
      "Chennai"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        13.2495,
        79.8749
      ],
      [
        12.7346,
        79.8593
      ],
      [
        13.0833,
        80.2582
      ]
    ],
    "deaths": 17,
    "deathsRaw": "17 in Tamil Nadu in MHA annual disaster series; some contemporaneous assessments reported 20",
    "injuries": 11,
    "evacuated": 41459,
    "damageCrore": 2070.04,
    "damageBasis": "₹2,070.04 crore state memorandum estimate for temporary restoration; MHA records ₹285.54 crore approved and ₹276.10 crore released from NDRF",
    "rainfallMm": null,
    "windKmh": 110,
    "infrastructure": "2189 houses/huts in MHA annual series; severe urban flooding, roads, power and drainage disruption",
    "sourceType": "Verified MHA + secondary assessment",
    "source": "MHA parliamentary data; Sphere India assessment; TN Government records",
    "sourceUrl": "https://sansad.in/getFile/loksabhaquestions/annex/184/AU288_lZFPXC.pdf?source=pqals",
    "limitations": "Casualty counts differ between snapshots; monetary value is a state restoration request, not final economic loss.",
    "variants": [],
    "notes": "Chennai airport runway submerged; Foxconn/Pegatron plants halted; second wave of flooding hit southern districts later in December"
  },
  {
    "id": "TN2023-04",
    "name": "Southern Tamil Nadu floods",
    "year": 2023,
    "date": "2023-12-17/2023-12-20",
    "hazard": "flood",
    "isHydro": true,
    "districts": [
      "Thoothukkudi",
      "Virudunagar",
      "Kanniyakumari",
      "Tirunelveli",
      "Ramanathapuram"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        8.9003,
        78.0032
      ],
      [
        9.351,
        78.4568
      ],
      [
        8.3245,
        77.365
      ],
      [
        8.839,
        77.5998
      ],
      [
        9.5189,
        78.6457
      ]
    ],
    "deaths": 61,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": 18214.52,
    "damageBasis": "₹18,214.52 crore sought for temporary + permanent restoration in state memorandum",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "18,088 houses/huts; 18,213 cattle; 248,303.5 ha cropped area in MHA annual series; roads, bridges and utilities damaged",
    "sourceType": "Verified Government of India + Tamil Nadu government",
    "source": "MHA annual disaster series; Tamil Nadu central-assistance memorandum summary",
    "sourceUrl": "https://sansad.in/getFile/loksabhaquestions/annex/184/AU288_lZFPXC.pdf?source=pqals",
    "limitations": "MHA annual series combines the flood disaster into a financial-year category; not every local event has a separate taluk record.",
    "variants": []
  },
  {
    "id": "TN2024-01",
    "name": "Gundayirappu/Vembakottai fireworks blast",
    "year": 2024,
    "date": "2024-02-17",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 10,
    "deathsRaw": null,
    "injuries": 6,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "4 of 74 rooms completely gutted; 1 partially damaged",
    "sourceType": "Media report citing officials",
    "source": "New Indian Express; Indian Express",
    "sourceUrl": "https://www.newindianexpress.com/states/tamil-nadu/2024/Feb/17/fatal-blast-claims-10-lives-in-tns-virudhunagar-district-firecracker-factory-explosion",
    "limitations": "No standardized economic-loss assessment located.",
    "variants": []
  },
  {
    "id": "TN2024-02",
    "name": "Sengamalapatti/Sivakasi fireworks blast",
    "year": 2024,
    "date": "2024-05-09",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 9,
    "deathsRaw": "9 in later PTI report; some early reports said 8",
    "injuries": 10,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "7 rooms completely gutted; nearby working sheds affected",
    "sourceType": "Media reports",
    "source": "Indian Express/PTI; Times of India",
    "sourceUrl": "https://indianexpress.com/article/cities/chennai/toll-firecracker-blast-tamil-nadu-sivakasi-9319048/",
    "limitations": "Casualty count changed as injured victims died; dataset records the later reported count and flags early discrepancy.",
    "variants": []
  },
  {
    "id": "TN2024-03",
    "name": "Panthuvarpatti fireworks-unit blast",
    "year": 2024,
    "date": "2024-06-29",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 4,
    "deathsRaw": null,
    "injuries": 1,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Factory rooms/buildings damaged; part of factory collapsed",
    "sourceType": "PTI-syndicated media report",
    "source": "NDTV/PTI; India Today",
    "sourceUrl": "https://www.ndtv.com/india-news/4-workers-killed-1-injured-in-firecracker-unit-blast-in-tamil-nadu-cops-5996611",
    "limitations": "No verified property-loss valuation.",
    "variants": []
  },
  {
    "id": "TN2024-04",
    "name": "Kalayarkurichchi/Sivakasi fireworks blast",
    "year": 2024,
    "date": "2024-07-09",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Virudunagar"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        9.351,
        78.4568
      ]
    ],
    "deaths": 2,
    "deathsRaw": null,
    "injuries": 2,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Factory unit damaged",
    "sourceType": "Media report",
    "source": "India Today",
    "sourceUrl": "https://www.indiatoday.in/india/tamil-nadu/story/tamil-nadu-virudhunagar-firecracker-factory-blast-sivakasi-2564521-2024-07-09",
    "limitations": "No economic-loss figure located.",
    "variants": []
  },
  {
    "id": "TN2024-05",
    "name": "Thiruvalankadu fireworks-unit blast",
    "year": 2024,
    "date": "2024-08-24",
    "hazard": "fireworks",
    "isHydro": false,
    "districts": [
      "Nagappattinam"
    ],
    "substitutedDistricts": [
      "Nagappattinam"
    ],
    "centers": [
      [
        10.894,
        79.7045
      ]
    ],
    "deaths": 1,
    "deathsRaw": null,
    "injuries": 3,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "Small-scale unit almost completely gutted",
    "sourceType": "Media report citing officials",
    "source": "New Indian Express",
    "sourceUrl": "https://www.newindianexpress.com/states/tamil-nadu/2024/Aug/25/one-killed-three-injured-in-firecracker-unit-blast-in-tamil-nadu",
    "limitations": "No event-level economic-loss estimate.",
    "variants": []
  },
  {
    "id": "TN2024-06",
    "name": "Kavaraipettai passenger-goods train collision",
    "year": 2024,
    "date": "2024-10-11",
    "hazard": "transport",
    "isHydro": false,
    "districts": [
      "Thiruvallur"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        13.2495,
        79.8749
      ]
    ],
    "deaths": 0,
    "deathsRaw": null,
    "injuries": 19,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": "No event-level infrastructure-loss estimate located",
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": "13 passenger coaches derailed; two goods wagons damaged; track/station operations disrupted",
    "sourceType": "Media/railway context; official station records",
    "source": "Contemporary media reporting; Southern Railway station records",
    "sourceUrl": "https://sr.indianrailways.gov.in/cris/uploads/files/1748432112041-List%20of%20stations%20as%20on%2001042025.pdf",
    "limitations": "No verified final repair-cost figure included; incident cause remained under investigation in contemporary reporting.",
    "variants": []
  },
  {
    "id": "TN2024-07",
    "name": "Cyclone Fengal",
    "year": 2024,
    "date": "2024-11-23/2024-12-02",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvallur",
      "Kancheepuram",
      "Viluppuram",
      "Vellore",
      "Chennai",
      "Cuddalore",
      "Dharmapuri",
      "Krishnagiri",
      "Tiruvannamalai"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        13.2495,
        79.8749
      ],
      [
        12.7346,
        79.8593
      ],
      [
        11.9551,
        79.3582
      ],
      [
        12.8292,
        79.1011
      ],
      [
        13.0833,
        80.2582
      ],
      [
        11.6364,
        79.4948
      ],
      [
        12.0968,
        78.2538
      ],
      [
        12.4804,
        78.0716
      ],
      [
        12.4223,
        79.2542
      ]
    ],
    "deaths": 40,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": 3104.93,
    "damageBasis": "₹3,104.93 crore immediate NDRF assistance projected in Tamil Nadu memorandum; later NDRF approval ₹522.34 crore",
    "rainfallMm": 500,
    "windKmh": null,
    "infrastructure": "10,331 houses/huts; 2,991 cattle; 380,985.97 ha cropped area; roads, culverts, tanks, power conductors/poles/transformers and Panchayat buildings damaged",
    "sourceType": "Verified Tamil Nadu Government + MHA/IMD",
    "source": "Tamil Nadu DIPR/CM memorandum; MHA parliamentary data; IMD cyclone bulletin",
    "sourceUrl": "https://dipr.tn.gov.in/ords/r/dipr/info-prdept103/press-release1?cs=13DxD5waJrs_bvHSaIg9qN7LcuFwHdKVX---rXK34DZAYShevf1wvdEBMGhJuECXQ751IbaRM6suwBkOl9v371A&p33_file_id=10223&request=APPLICATION_PROCESS%3DGET_FILE",
    "limitations": "Early December state snapshot listed 12 deaths, while later government series gives 40 for the broader event; use the later consolidated figure for the statewide event.",
    "variants": [
      "3 deaths reported in the summary dataset"
    ],
    "notes": "Declared a severe natural disaster by TN Govt for relief fund release"
  },
  {
    "id": "TNS-2025-ditwah",
    "name": "Cyclone Ditwah",
    "year": 2025,
    "date": "2025 November-December",
    "hazard": "cyclone",
    "isHydro": true,
    "districts": [
      "Thiruvarur",
      "Nagappattinam"
    ],
    "substitutedDistricts": [],
    "centers": [
      [
        10.6587,
        79.5655
      ],
      [
        10.894,
        79.7045
      ]
    ],
    "deaths": 3,
    "deathsRaw": null,
    "injuries": null,
    "evacuated": null,
    "damageCrore": null,
    "damageBasis": null,
    "rainfallMm": null,
    "windKmh": null,
    "infrastructure": null,
    "sourceType": "Summary dataset",
    "source": "tn_disasters_dataset.csv",
    "sourceUrl": null,
    "limitations": "From the summary dataset, which carries no per-event source URL. Treat as indicative.",
    "notes": "~57,000 hectares of farmland affected across three delta districts",
    "variants": []
  }
];

/** Cyclone, flood, rain and drought events only. */
export const TN_HYDRO_EVENTS: TnDisasterEvent[] = TN_DISASTERS.filter((e) => e.isHydro);

/**
 * How many recorded flood or cyclone events named each district.
 *
 * Drought is excluded deliberately. The 2019 declaration covered 18 districts
 * at once, most of them inland, and counting it would rank Dharmapuri and
 * Krishnagiri alongside Chennai and Cuddalore for *flood* exposure - which is
 * the opposite of what the record shows.
 */
export const TN_DISTRICT_FLOOD_COUNTS: Record<string, number> = {
  "Chennai": 6,
  "Cuddalore": 6,
  "Kancheepuram": 6,
  "Thiruvallur": 5,
  "Nagappattinam": 4,
  "Ramanathapuram": 3,
  "Thanjavur": 3,
  "Thiruvarur": 3,
  "Thoothukkudi": 3,
  "Tirunelveli": 3,
  "Viluppuram": 3,
  "Kanniyakumari": 2,
  "Tiruvannamalai": 2,
  "Vellore": 2,
  "Dharmapuri": 1,
  "Krishnagiri": 1,
  "Pudukkottai": 1,
  "Virudunagar": 1
};

/**
 * Centroid of every Tamil Nadu district polygon, for nearest-district lookup.
 *
 * Vertex-average centroids, and matching a point to the nearest one is a
 * Voronoi approximation rather than a point-in-polygon test - which is why
 * the UI says "nearest district" and not "this district".
 */
export const TN_DISTRICT_CENTROIDS: Record<string, [number, number]> = {
  "Ariyalur": [
    11.2104,
    79.2066
  ],
  "Chennai": [
    13.0833,
    80.2582
  ],
  "Coimbatore": [
    10.9317,
    76.9717
  ],
  "Cuddalore": [
    11.6364,
    79.4948
  ],
  "Dharmapuri": [
    12.0968,
    78.2538
  ],
  "Dindigul": [
    10.4105,
    77.7945
  ],
  "Erode": [
    11.4898,
    77.3503
  ],
  "Kancheepuram": [
    12.7346,
    79.8593
  ],
  "Kanniyakumari": [
    8.3245,
    77.365
  ],
  "Karur": [
    10.7897,
    78.1032
  ],
  "Krishnagiri": [
    12.4804,
    78.0716
  ],
  "Madurai": [
    9.903,
    78.0481
  ],
  "Namakkal": [
    11.364,
    78.1309
  ],
  "Perambalur": [
    11.2675,
    78.8749
  ],
  "Pudukkottai": [
    10.3965,
    78.9026
  ],
  "Ramanathapuram": [
    9.5189,
    78.6457
  ],
  "Salem": [
    11.629,
    78.2579
  ],
  "Sivaganga": [
    9.9573,
    78.556
  ],
  "Thanjavur": [
    10.5941,
    79.2461
  ],
  "The Nilgiris": [
    11.4471,
    76.5987
  ],
  "Theni": [
    9.9319,
    77.4373
  ],
  "Thiruvallur": [
    13.2495,
    79.8749
  ],
  "Thiruvarur": [
    10.6587,
    79.5655
  ],
  "Thoothukkudi": [
    8.9003,
    78.0032
  ],
  "Tiruchirappalli": [
    10.8314,
    78.5587
  ],
  "Tirunelveli": [
    8.839,
    77.5998
  ],
  "Tiruppur": [
    10.8482,
    77.3985
  ],
  "Tiruvannamalai": [
    12.4223,
    79.2542
  ],
  "Vellore": [
    12.8292,
    79.1011
  ],
  "Viluppuram": [
    11.9551,
    79.3582
  ],
  "Virudunagar": [
    9.351,
    78.4568
  ],
  "Nagappattinam": [
    10.894,
    79.7045
  ]
};

/** The highest count above, so a caller can normalise without recomputing. */
export const TN_MAX_FLOOD_COUNT = 6;
